# Generated by Django 4.2.20 on 2025-05-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('akcie', 'Akcie'), ('etf', 'ETF'), ('krypto', 'Kryptoměna'), ('nemovitost', 'Nemovitost'), ('jine', 'Jiné')], max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=20, null=True)),
                ('mena', models.CharField(default='CZK', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poznamka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('investice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poznamky', to='denik.investice')),
            ],
        ),
        migrations.CreateModel(
            name='Transakce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('cena_za_jednotku', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mnozstvi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.CharField(choices=[('nákup', 'Nákup'), ('prodej', 'Prodej')], max_length=10)),
                ('investice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transakce', to='denik.investice')),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='note',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
