# Generated by Django 4.2.20 on 2025-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denik', '0002_investice_poznamka_transakce_remove_investment_asset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obchod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('aktivum', models.CharField(max_length=100)),
                ('mnozstvi', models.FloatField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='poznamka',
            old_name='datum',
            new_name='datum_vytvoreni',
        ),
        migrations.RenameField(
            model_name='poznamka',
            old_name='text',
            new_name='obsah',
        ),
        migrations.RemoveField(
            model_name='poznamka',
            name='investice',
        ),
        migrations.AddField(
            model_name='poznamka',
            name='titulek',
            field=models.CharField(default='titulek', max_length=100),
            preserve_default=False,
        ),
    ]
