# Generated by Django 4.2.20 on 2025-05-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denik', '0003_obchod_rename_datum_poznamka_datum_vytvoreni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transakce',
            old_name='cena_za_jednotku',
            new_name='cena',
        ),
        migrations.RemoveField(
            model_name='obchod',
            name='nazev',
        ),
        migrations.RemoveField(
            model_name='transakce',
            name='typ',
        ),
        migrations.AddField(
            model_name='poznamka',
            name='investice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poznamky', to='denik.investice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obchod',
            name='aktivum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obchody', to='denik.investice'),
        ),
        migrations.AlterField(
            model_name='obchod',
            name='mnozstvi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
