# Generated by Django 4.2.20 on 2025-05-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denik', '0004_rename_cena_za_jednotku_transakce_cena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investice',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
