# Generated by Django 4.2.20 on 2025-05-10 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('denik', '0006_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulaceInvestice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('hodnota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denik.investice')),
            ],
        ),
    ]
