# Generated by Django 4.2.20 on 2025-05-13 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denik', '0009_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='investice',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investice', to=settings.AUTH_USER_MODEL),
        ),
    ]
